name: ci

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - run: npm run build:examples
      - run: npm run docs:build

  cpp:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: configure
        run: cmake --preset windows-debug
      - name: build
        run: cmake --build --preset windows-debug
      - name: test
        run: ctest --preset windows-debug
